language: node_js
node_js:
- node

install:
- npm install

before_script: 

script: 

deploy:
- provider: surge
  skip_cleanup: true
  project: "./"
  domain: nak-sued-fotocontest.surge.sh
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: curl --ftp-create-dirs -T $f -u $FTP_USER:$FTP_PASS ftp://fotocontest.nak-sued.de/web/$f
