language: node_js
node_js:
- node

install:
- npm install

before_script: 

script: 

after_success:
  provider: surge
  project: "./"
  domain: nak-sued-fotocontest.surge.sh
  on:
    branch: develop
  
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
