language: node_js
sudo: false
node_js:
- node
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem update --system

install:
- npm install
before_script:
- npm install -g surge 

script:
- surge -d nak-sued-fotocontest.surge.sh
